<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\KalenderPendidikan;

class KalenderPendidikanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate / kosongkan data lama agar urutan rapi dan tidak duplikat
        KalenderPendidikan::truncate();

        $events = [
            [
                'nama_kegiatan'   => 'Daftar Ulang SPMB SMA/SMK Maung',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-06-09',
                'tanggal_selesai' => '2026-06-10',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#3b82f6',
                'keterangan'      => 'Jenjang: SMA / SMK',
                'created_by'      => 'Kurikulum & Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Daftar Ulang SPMB SMA/SMK Tahap I',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-06-26',
                'tanggal_selesai' => '2026-06-29',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#3b82f6',
                'keterangan'      => 'Jenjang: SMA / SMK',
                'created_by'      => 'Kurikulum & Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Olimpiade Olahraga Siswa Nasional (O2SN)',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-07-02',
                'tanggal_selesai' => '2026-07-03',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tingkat Provinsi',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Lomba Debat Bahasa Indonesia (LDBI)',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-07-11',
                'tanggal_selesai' => '2026-07-12',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tingkat Provinsi',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Daftar Ulang SPMB SMA/SMK Tahap 2',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-07-13',
                'tanggal_selesai' => '2026-07-14',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#3b82f6',
                'keterangan'      => 'Jenjang: SMA / SMK',
                'created_by'      => 'Kurikulum & Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'FLS3N Pendidikan Khusus (Perkiraan)',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-07-13',
                'tanggal_selesai' => '2026-07-18',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Daring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Penyelarasan Kurikulum SMK *)',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-07-14',
                'tanggal_selesai' => '2026-07-14',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#6366f1',
                'keterangan'      => 'SMK (*)',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Hari Pertama Masuk Sekolah Semester 1',
                'tipe'            => 'hari_efektif',
                'tanggal_mulai'   => '2026-07-15',
                'tanggal_selesai' => '2026-07-15',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#06b6d4',
                'keterangan'      => 'Semua Jenjang - Awal Semester Ganjil TA 2026/2027',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Masa Pengenalan Lingkungan Sekolah (MPLS)',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-07-15',
                'tanggal_selesai' => '2026-07-21',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#6366f1',
                'keterangan'      => 'Siswa Baru (Pelaksanaan: 15–17 & 20–21 Juli 2026)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Lomba Kompetensi Siswa (LKS) Dikmen',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-07-26',
                'tanggal_selesai' => '2026-08-01',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Daring & Luring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Olimpiade Sains Nasional (OSN) Dikmen',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-07-27',
                'tanggal_selesai' => '2026-07-29',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tingkat Provinsi',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Lomba Kompetensi Siswa (LKS) Diksus',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-08-03',
                'tanggal_selesai' => '2026-08-08',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Daring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Pelaksanaan Survei Lingkungan Belajar (Sulingjar)',
                'tipe'            => 'ujian_asesmen',
                'tanggal_mulai'   => '2026-08-03',
                'tanggal_selesai' => '2026-08-31',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#10b981',
                'keterangan'      => 'PAUD, SD, SMP, SMA, SMK',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'FLS3N Jenjang Dikmen (SMA/SMK)',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-08-08',
                'tanggal_selesai' => '2026-08-08',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tingkat Provinsi',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Hari Pramuka Nasional',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-08-14',
                'tanggal_selesai' => '2026-08-14',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#6366f1',
                'keterangan'      => 'Peringatan Nasional (Kegiatan Upacara / Apel)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Libur Proklamasi Kemerdekaan RI',
                'tipe'            => 'libur_nasional',
                'tanggal_mulai'   => '2026-08-17',
                'tanggal_selesai' => '2026-08-17',
                'libur_pd'        => true,
                'libur_guru'      => true,
                'libur_tendik'    => true,
                'warna'           => '#ef4444',
                'keterangan'      => 'Libur Nasional - HUT Kemerdekaan RI Ke-81',
                'created_by'      => 'Administrator',
            ],
            [
                'nama_kegiatan'   => 'O2SN Jenjang Pendidikan Dasar',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-08-17',
                'tanggal_selesai' => '2026-08-23',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Luring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Libur Maulid Nabi Muhammad SAW',
                'tipe'            => 'libur_nasional',
                'tanggal_mulai'   => '2026-08-25',
                'tanggal_selesai' => '2026-08-25',
                'libur_pd'        => true,
                'libur_guru'      => true,
                'libur_tendik'    => true,
                'warna'           => '#ef4444',
                'keterangan'      => 'Libur Nasional - Maulid Nabi Muhammad SAW 1448 H',
                'created_by'      => 'Administrator',
            ],
            [
                'nama_kegiatan'   => 'OSN Jenjang Pendidikan Dasar',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-08-25',
                'tanggal_selesai' => '2026-08-31',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Daring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Lomba Debat Indonesia (LDI) Dikmen',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-08-31',
                'tanggal_selesai' => '2026-09-06',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Daring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Festival Inovasi & Kewirausahaan Siswa (FIKSI) Dikmen',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-09-07',
                'tanggal_selesai' => '2026-09-12',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'O2SN Jenjang Pendidikan Khusus',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-09-07',
                'tanggal_selesai' => '2026-09-12',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Luring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'O2SN Jenjang Pendidikan Menengah',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-09-07',
                'tanggal_selesai' => '2026-09-13',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Luring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'OSN Jenjang Pendidikan Menengah',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-09-14',
                'tanggal_selesai' => '2026-09-20',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Luring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Olimpiade Penelitian Siswa Indonesia (OPSI) Dikmen',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-09-24',
                'tanggal_selesai' => '2026-09-30',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Luring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'FLS3N Jenjang Pendidikan Dasar',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-09-28',
                'tanggal_selesai' => '2026-10-03',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Daring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'FLS3N Jenjang Pendidikan Menengah',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-10-05',
                'tanggal_selesai' => '2026-10-10',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Daring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Gala Siswa Indonesia (GSI) Dikdas',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-10-20',
                'tanggal_selesai' => '2026-10-31',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tk. Nasional (Luring)',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Tes Kompetensi Akademik (TKA) Gelombang 1 & 2',
                'tipe'            => 'ujian_asesmen',
                'tanggal_mulai'   => '2026-10-26',
                'tanggal_selesai' => '2026-11-08',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#10b981',
                'keterangan'      => 'SMA/MA/SMALB/Paket C/SMK',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Uji Kompetensi Keahlian (UKK) 2026',
                'tipe'            => 'ujian_asesmen',
                'tanggal_mulai'   => '2026-11-09',
                'tanggal_selesai' => '2026-12-11',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#10b981',
                'keterangan'      => 'SMK (Kelas XII & XIII)',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Tes Kompetensi Akademik (TKA) Susulan',
                'tipe'            => 'ujian_asesmen',
                'tanggal_mulai'   => '2026-11-16',
                'tanggal_selesai' => '2026-11-29',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#10b981',
                'keterangan'      => 'SMA/MA/SMALB/Paket C/SMK',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Gelar Aksi Karakter Siswa Indonesia',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-11-21',
                'tanggal_selesai' => '2026-11-21',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#8b5cf6',
                'keterangan'      => 'Tingkat Provinsi',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Hari Guru Nasional',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-11-25',
                'tanggal_selesai' => '2026-11-25',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#6366f1',
                'keterangan'      => 'Peringatan Nasional (Kegiatan Upacara / Apel HGN)',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Asesmen Sumatif Akhir Semester (ASAS)',
                'tipe'            => 'ujian_asesmen',
                'tanggal_mulai'   => '2026-11-30',
                'tanggal_selesai' => '2026-12-11',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#10b981',
                'keterangan'      => 'Semester Ganjil TA 2026/2027',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Hari Disabilitas Internasional',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-12-03',
                'tanggal_selesai' => '2026-12-03',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#6366f1',
                'keterangan'      => 'Peringatan Internasional',
                'created_by'      => 'Kesiswaan',
            ],
            [
                'nama_kegiatan'   => 'Penetapan & Pembagian Rapor Semester 1',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2026-12-23',
                'tanggal_selesai' => '2026-12-23',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#6366f1',
                'keterangan'      => 'Semester Ganjil TA 2026/2027',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Cuti Bersama Hari Raya Natal',
                'tipe'            => 'libur_nasional',
                'tanggal_mulai'   => '2026-12-24',
                'tanggal_selesai' => '2026-12-24',
                'libur_pd'        => true,
                'libur_guru'      => true,
                'libur_tendik'    => true,
                'warna'           => '#ef4444',
                'keterangan'      => 'Hari Libur Cuti Bersama Nasional',
                'created_by'      => 'Administrator',
            ],
            [
                'nama_kegiatan'   => 'Libur Hari Raya Natal',
                'tipe'            => 'libur_nasional',
                'tanggal_mulai'   => '2026-12-25',
                'tanggal_selesai' => '2026-12-25',
                'libur_pd'        => true,
                'libur_guru'      => true,
                'libur_tendik'    => true,
                'warna'           => '#ef4444',
                'keterangan'      => 'Libur Nasional Hari Raya Natal',
                'created_by'      => 'Administrator',
            ],
            [
                'nama_kegiatan'   => 'Libur Semester 1',
                'tipe'            => 'libur_semester',
                'tanggal_mulai'   => '2026-12-28',
                'tanggal_selesai' => '2027-01-08',
                'libur_pd'        => true,
                'libur_guru'      => true,
                'libur_tendik'    => false,
                'warna'           => '#f59e0b',
                'keterangan'      => 'Libur Sekolah Semester Ganjil TA 2026/2027',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Hari Pertama Masuk Sekolah Semester 2',
                'tipe'            => 'hari_efektif',
                'tanggal_mulai'   => '2027-01-11',
                'tanggal_selesai' => '2027-01-11',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#06b6d4',
                'keterangan'      => 'Semester Genap TA 2026/2027',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Perkiraan Libur Awal Ramadan 1448 H **)',
                'tipe'            => 'libur_khusus',
                'tanggal_mulai'   => '2027-02-08',
                'tanggal_selesai' => '2027-02-12',
                'libur_pd'        => true,
                'libur_guru'      => true,
                'libur_tendik'    => false,
                'warna'           => '#ec4899',
                'keterangan'      => 'Libur Khusus Satuan Pendidikan (**)',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Perkiraan Libur Hari Raya Idul Fitri 1448 H',
                'tipe'            => 'libur_nasional',
                'tanggal_mulai'   => '2027-03-08',
                'tanggal_selesai' => '2027-03-19',
                'libur_pd'        => true,
                'libur_guru'      => true,
                'libur_tendik'    => true,
                'warna'           => '#ef4444',
                'keterangan'      => 'Libur Hari Raya Idul Fitri 1448 H & Cuti Bersama',
                'created_by'      => 'Administrator',
            ],
            [
                'nama_kegiatan'   => 'Penetapan & Pembagian Rapor Semester 2 ***)',
                'tipe'            => 'kegiatan_sekolah',
                'tanggal_mulai'   => '2027-06-25',
                'tanggal_selesai' => '2027-06-25',
                'libur_pd'        => false,
                'libur_guru'      => false,
                'libur_tendik'    => false,
                'warna'           => '#6366f1',
                'keterangan'      => 'Semester Genap TA 2026/2027 (***)',
                'created_by'      => 'Kurikulum',
            ],
            [
                'nama_kegiatan'   => 'Libur Akhir Tahun Ajaran ****)',
                'tipe'            => 'libur_semester',
                'tanggal_mulai'   => '2027-06-28',
                'tanggal_selesai' => '2027-07-09',
                'libur_pd'        => true,
                'libur_guru'      => true,
                'libur_tendik'    => false,
                'warna'           => '#f59e0b',
                'keterangan'      => 'Libur Kenaikan Kelas / Akhir Tahun Ajaran 2026/2027 (****)',
                'created_by'      => 'Kurikulum',
            ],
        ];

        foreach ($events as $event) {
            KalenderPendidikan::create($event);
        }
    }
}
