<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DapodikController;
use App\Http\Controllers\InstallController;
use App\Http\Controllers\UpdateController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\KompetensiKeahlianController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Installer Routes
Route::get('/install', [InstallController::class, 'index'])->name('install.index');
Route::post('/install', [InstallController::class, 'process'])->name('install.process');

// Public Routes
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('/api/check-nisn', [HomeController::class, 'checkNisn'])->name('api.check-nisn');

// Kartu Pelajar Digital — Verifikasi Publik & Direct Scan (Privacy-by-Design)
Route::get('/v/{nisn}', [\App\Http\Controllers\KartuPelajarController::class, 'verify'])->name('kartu-pelajar.verify-short');
Route::get('/verifikasi-pelajar/{nisn}', [\App\Http\Controllers\KartuPelajarController::class, 'verify'])->name('kartu-pelajar.verify');
Route::get('/kartu-pelajar/preview/{nisn}', [\App\Http\Controllers\KartuPelajarController::class, 'preview'])->name('kartu-pelajar.preview');

// SAE Forms — Formulir & Survei Publik
Route::get('/f/{slug}', [\App\Http\Controllers\FormulirController::class, 'showPublic'])->name('formulir.public');
Route::post('/f/{slug}', [\App\Http\Controllers\FormulirController::class, 'submitPublic'])->name('formulir.submit');
Route::get('/f/{slug}/sukses/{respon}', [\App\Http\Controllers\FormulirController::class, 'successPublic'])->name('formulir.success');
Route::get('/formulir/{slug}', [\App\Http\Controllers\FormulirController::class, 'showPublic']);

// Auth Routes (Multi-User)
Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login.post');
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
Route::get('/logout', [AuthController::class, 'logout']);
Route::get('/auth/update-password-wajib', [AuthController::class, 'showForceUpdatePassword'])->name('auth.force-update-password');
Route::post('/auth/update-password-wajib', [AuthController::class, 'processForceUpdatePassword'])->name('auth.force-update-password.post');
Route::get('/auth/cancel-force-update', [AuthController::class, 'cancelForceUpdate'])->name('auth.cancel-force-update');

// Dashboard Multi-User Routes (Protected)
Route::prefix('dashboard')->name('dashboard.')->group(function () {

    // Modul agenda-kbm (Auto-generated by sae:make-module)
    Route::get('/agenda-kbm', [\App\Http\Controllers\AgendaKbmController::class, 'index'])->name('agenda-kbm.index')->middleware('permission:menu_agenda_kbm,read');
    Route::get('/agenda-kbm/next-pertemuan', [\App\Http\Controllers\AgendaKbmController::class, 'getNextPertemuan'])->name('agenda-kbm.next-pertemuan')->middleware('permission:menu_agenda_kbm,read');
    Route::get('/agenda-kbm/cetak', [\App\Http\Controllers\AgendaKbmController::class, 'cetak'])->name('agenda-kbm.cetak')->middleware('permission:menu_agenda_kbm,read');
    Route::post('/agenda-kbm', [\App\Http\Controllers\AgendaKbmController::class, 'store'])->name('agenda-kbm.store')->middleware('permission:menu_agenda_kbm,create');
    Route::get('/agenda-kbm/{id}', [\App\Http\Controllers\AgendaKbmController::class, 'show'])->name('agenda-kbm.show')->middleware('permission:menu_agenda_kbm,read');
    Route::put('/agenda-kbm/{id}', [\App\Http\Controllers\AgendaKbmController::class, 'update'])->name('agenda-kbm.update')->middleware('permission:menu_agenda_kbm,update');
    Route::delete('/agenda-kbm/{id}', [\App\Http\Controllers\AgendaKbmController::class, 'destroy'])->name('agenda-kbm.destroy')->middleware('permission:menu_agenda_kbm,delete');

    // Modul presensi-mengajar (Auto-generated by sae:make-module)
    Route::get('/presensi-mengajar', [\App\Http\Controllers\PresensiMengajarController::class, 'index'])->name('presensi-mengajar.index')->middleware('permission:menu_presensi_mengajar,read');
    Route::post('/presensi-mengajar', [\App\Http\Controllers\PresensiMengajarController::class, 'store'])->name('presensi-mengajar.store')->middleware('permission:menu_presensi_mengajar,create');
    Route::get('/presensi-mengajar/{id}', [\App\Http\Controllers\PresensiMengajarController::class, 'show'])->name('presensi-mengajar.show')->middleware('permission:menu_presensi_mengajar,read');
    Route::put('/presensi-mengajar/{id}', [\App\Http\Controllers\PresensiMengajarController::class, 'update'])->name('presensi-mengajar.update')->middleware('permission:menu_presensi_mengajar,update');
    Route::delete('/presensi-mengajar/{id}', [\App\Http\Controllers\PresensiMengajarController::class, 'destroy'])->name('presensi-mengajar.destroy')->middleware('permission:menu_presensi_mengajar,delete');
    Route::get('/admin', [DashboardController::class, 'admin'])->name('admin');
    Route::get('/guru', [DashboardController::class, 'guru'])->name('guru');
    Route::get('/tendik', [DashboardController::class, 'tendik'])->name('tendik');
    Route::get('/peserta-didik', [DashboardController::class, 'pesertaDidik'])->name('peserta-didik');
    Route::get('/peserta_didik', [DashboardController::class, 'pesertaDidik'])->name('peserta_didik');

    // Profil Pengguna & Keamanan Akun
    Route::get('/profil', [\App\Http\Controllers\ProfileController::class, 'index'])->name('profile');
    Route::put('/profil/password', [\App\Http\Controllers\ProfileController::class, 'updatePassword'])->name('profile.password');
    Route::put('/profil/kontak', [\App\Http\Controllers\ProfileController::class, 'updateContact'])->name('profile.contact');

    // Tarik Data Dapodik
    Route::get('/tarik-data', [DapodikController::class, 'index'])->name('dapodik')->middleware('permission:menu_dapodik');
    Route::post('/tarik-data/apikey', [DapodikController::class, 'generateApiKey'])->name('dapodik.apikey')->middleware('permission:fitur_dapodik_sync');

    // Manajemen Pengguna (4 Tab: Admin, Guru, Tendik, Peserta Didik)
    Route::get('/pengguna', [UserController::class, 'index'])->name('pengguna.index')->middleware('permission:menu_pengguna');
    Route::put('/pengguna/{pengguna}', [UserController::class, 'update'])->name('pengguna.update')->middleware('permission:fitur_pengguna_edit');
    Route::delete('/pengguna/{pengguna}', [UserController::class, 'destroy'])->name('pengguna.destroy')->middleware('permission:fitur_pengguna_hapus');
    Route::post('/pengguna/{pengguna}/reset-password', [UserController::class, 'resetPassword'])->name('pengguna.resetPassword')->middleware('permission:fitur_pengguna_reset');

    // Update Sistem
    Route::get('/update', [UpdateController::class, 'index'])->name('update')->middleware('permission:menu_update');
    Route::get('/update/check', [UpdateController::class, 'check'])->name('update.check')->middleware('permission:menu_update');
    Route::post('/update/execute', [UpdateController::class, 'execute'])->name('update.execute')->middleware('permission:fitur_system_update');
    Route::get('/update/diagnose', [UpdateController::class, 'diagnose'])->name('update.diagnose')->middleware('permission:menu_update');

    // Pengaturan Hak Akses (Role & Permission)
    Route::get('/hak-akses', [PermissionController::class, 'index'])->name('hak-akses.index')->middleware('permission:menu_hak_akses,read');
    Route::post('/hak-akses/toggle', [PermissionController::class, 'toggle'])->name('hak-akses.toggle')->middleware('permission:menu_hak_akses,update');
    Route::post('/hak-akses/sync', [PermissionController::class, 'sync'])->name('hak-akses.sync')->middleware('permission:menu_hak_akses,update');
    Route::post('/hak-akses/reset', [PermissionController::class, 'resetDefault'])->name('hak-akses.reset')->middleware('permission:menu_hak_akses,update');
    Route::post('/hak-akses/add-module', [PermissionController::class, 'addModule'])->name('hak-akses.add-module')->middleware('permission:menu_hak_akses,create');
    Route::post('/hak-akses/remove-module', [PermissionController::class, 'removeModule'])->name('hak-akses.remove-module')->middleware('permission:menu_hak_akses,delete');
    Route::post('/hak-akses/tugas-tambahan/store', [PermissionController::class, 'storeTugasTambahan'])->name('hak-akses.tugas-tambahan.store')->middleware('permission:menu_hak_akses,create');
    Route::delete('/hak-akses/tugas-tambahan/{id}', [PermissionController::class, 'destroyTugasTambahan'])->name('hak-akses.tugas-tambahan.destroy')->middleware('permission:menu_hak_akses,delete');
    Route::post('/hak-akses/tugas-tambahan/sync-wali', [PermissionController::class, 'syncWaliKelas'])->name('hak-akses.tugas-tambahan.sync-wali')->middleware('permission:menu_hak_akses,update');

    // Pengaturan — Identitas Sekolah (Sumber: Sekolah Dapodik)
    Route::get('/identitas-sekolah', [\App\Http\Controllers\IdentitasSekolahController::class, 'index'])->name('identitas-sekolah.index')->middleware('permission:menu_pengaturan,read');
    Route::put('/identitas-sekolah', [\App\Http\Controllers\IdentitasSekolahController::class, 'update'])->name('identitas-sekolah.update')->middleware('permission:menu_pengaturan,update');
    Route::post('/identitas-sekolah/upload-logo', [\App\Http\Controllers\IdentitasSekolahController::class, 'uploadLogo'])->name('identitas-sekolah.upload-logo')->middleware('permission:menu_pengaturan,update');
    Route::delete('/identitas-sekolah/delete-logo', [\App\Http\Controllers\IdentitasSekolahController::class, 'deleteLogo'])->name('identitas-sekolah.delete-logo')->middleware('permission:menu_pengaturan,delete');
    Route::post('/identitas-sekolah/upload-kop', [\App\Http\Controllers\IdentitasSekolahController::class, 'uploadKop'])->name('identitas-sekolah.upload-kop')->middleware('permission:menu_pengaturan,update');
    Route::delete('/identitas-sekolah/delete-kop', [\App\Http\Controllers\IdentitasSekolahController::class, 'deleteKop'])->name('identitas-sekolah.delete-kop')->middleware('permission:menu_pengaturan,delete');

    // Layanan Digital — Pengumuman & Broadcast
    Route::get('/informasi', [\App\Http\Controllers\PengumumanController::class, 'pengguna'])->name('informasi.index');
    Route::post('/informasi/mark-all-read', [\App\Http\Controllers\PengumumanController::class, 'markAllRead'])->name('informasi.mark-all-read');
    Route::post('/informasi/{id}/mark-read', [\App\Http\Controllers\PengumumanController::class, 'markSingleRead'])->name('informasi.mark-read');
    Route::get('/informasi/{id}/detail', [\App\Http\Controllers\PengumumanController::class, 'detail'])->name('informasi.detail');
    Route::get('/pengumuman', [\App\Http\Controllers\PengumumanController::class, 'index'])->name('pengumuman.index')->middleware('permission:menu_pengumuman,read');
    Route::post('/pengumuman', [\App\Http\Controllers\PengumumanController::class, 'store'])->name('pengumuman.store')->middleware('permission:menu_pengumuman,create');
    Route::put('/pengumuman/{id}', [\App\Http\Controllers\PengumumanController::class, 'update'])->name('pengumuman.update')->middleware('permission:menu_pengumuman,update');
    Route::delete('/pengumuman/{id}', [\App\Http\Controllers\PengumumanController::class, 'destroy'])->name('pengumuman.destroy')->middleware('permission:menu_pengumuman,delete');
    Route::post('/pengumuman/{id}/toggle', [\App\Http\Controllers\PengumumanController::class, 'toggle'])->name('pengumuman.toggle')->middleware('permission:menu_pengumuman,update');

    // Layanan Digital — Formulir & Survei (SAE Form / OpnForm)
    Route::get('/formulir', [\App\Http\Controllers\FormulirController::class, 'index'])->name('formulir.index')->middleware('permission:menu_formulir,read');
    Route::get('/formulir/buat', [\App\Http\Controllers\FormulirController::class, 'create'])->name('formulir.create')->middleware('permission:menu_formulir,create');
    Route::post('/formulir', [\App\Http\Controllers\FormulirController::class, 'store'])->name('formulir.store')->middleware('permission:menu_formulir,create');
    Route::get('/formulir/{id}/edit', [\App\Http\Controllers\FormulirController::class, 'edit'])->name('formulir.edit')->middleware('permission:menu_formulir,update');
    Route::put('/formulir/{id}', [\App\Http\Controllers\FormulirController::class, 'update'])->name('formulir.update')->middleware('permission:menu_formulir,update');
    Route::delete('/formulir/{id}', [\App\Http\Controllers\FormulirController::class, 'destroy'])->name('formulir.destroy')->middleware('permission:menu_formulir,delete');
    Route::post('/formulir/{id}/toggle', [\App\Http\Controllers\FormulirController::class, 'toggle'])->name('formulir.toggle')->middleware('permission:menu_formulir,update');
    Route::post('/formulir/{id}/duplikasi', [\App\Http\Controllers\FormulirController::class, 'duplicate'])->name('formulir.duplicate')->middleware('permission:menu_formulir,create');
    Route::get('/formulir/{id}/respon', [\App\Http\Controllers\FormulirController::class, 'responses'])->name('formulir.responses')->middleware('permission:menu_formulir,read');
    Route::get('/formulir/{id}/export-csv', [\App\Http\Controllers\FormulirController::class, 'exportCsv'])->name('formulir.export-csv')->middleware('permission:menu_formulir,read');
    Route::delete('/formulir/{id}/respon/{responId}', [\App\Http\Controllers\FormulirController::class, 'deleteResponse'])->name('formulir.delete-response')->middleware('permission:menu_formulir,delete');

    // Layanan Digital — Presensi & RFID Realtime
    Route::get('/presensi', [\App\Http\Controllers\PresensiController::class, 'index'])->name('presensi.index')->middleware('permission:menu_rfid,read');
    Route::get('/presensi/scan', [\App\Http\Controllers\PresensiController::class, 'scanKiosk'])->name('presensi.scan')->middleware('permission:menu_rfid,read');
    Route::post('/presensi/scan/process', [\App\Http\Controllers\PresensiController::class, 'processScan'])->name('presensi.scan.process')->middleware('permission:menu_rfid,read');
    Route::get('/presensi/live-log', [\App\Http\Controllers\PresensiController::class, 'getLiveLog'])->name('presensi.live-log')->middleware('permission:menu_rfid,read');
    Route::post('/presensi/rfid/assign', [\App\Http\Controllers\PresensiController::class, 'assignRfid'])->name('presensi.rfid.assign')->middleware('permission:menu_rfid,update');
    Route::post('/presensi/pengaturan', [\App\Http\Controllers\PresensiController::class, 'updatePengaturan'])->name('presensi.pengaturan.update')->middleware('permission:menu_rfid,update');
    Route::get('/presensi/export', [\App\Http\Controllers\PresensiController::class, 'export'])->name('presensi.export')->middleware('permission:menu_rfid,read');
    Route::post('/presensi/izin/{id}/verifikasi', [\App\Http\Controllers\PresensiController::class, 'verifikasiIzin'])->name('presensi.izin.verifikasi')->middleware('permission:menu_rfid,update');

    // Administrasi Guru — Presensi Kelas (Wali Kelas & Guru)
    Route::get('/presensi/kelas', [\App\Http\Controllers\PresensiController::class, 'kelas'])->name('presensi.kelas')->middleware('permission:menu_presensi_peserta_didik,read');
    Route::post('/presensi/kelas/status', [\App\Http\Controllers\PresensiController::class, 'updateStatusKelas'])->name('presensi.kelas.status')->middleware('permission:menu_presensi_peserta_didik,update');
    Route::post('/presensi/kelas/auto-alpha', [\App\Http\Controllers\PresensiController::class, 'tandaiAlphaRombel'])->name('presensi.kelas.auto-alpha')->middleware('permission:menu_presensi_peserta_didik,update');

    // Portal Peserta Didik — Riwayat Presensi Saya
    Route::get('/presensi/saya', [\App\Http\Controllers\PresensiController::class, 'riwayatSaya'])->name('presensi.riwayat-saya')->middleware('permission:menu_riwayat_rfid,read');
    Route::post('/presensi/saya/izin', [\App\Http\Controllers\PresensiController::class, 'pengajuanIzin'])->name('presensi.saya.izin')->middleware('permission:menu_riwayat_rfid,create');

    // Master Data — Kompetensi Keahlian (Sumber: Rombongan Belajar)
    Route::get('/master-data/kompetensi-keahlian', [KompetensiKeahlianController::class, 'index'])->name('kompetensi-keahlian.index')->middleware('permission:menu_kompetensi_keahlian,read');
    Route::get('/master-data/kompetensi-keahlian/{kode}/rombel', [KompetensiKeahlianController::class, 'showRombel'])->name('kompetensi-keahlian.rombel')->middleware('permission:menu_kompetensi_keahlian,read');
    Route::post('/master-data/kompetensi-keahlian/{kode}/logo', [KompetensiKeahlianController::class, 'uploadLogo'])->name('kompetensi-keahlian.upload-logo')->middleware('permission:menu_kompetensi_keahlian,update');
    Route::delete('/master-data/kompetensi-keahlian/{kode}/logo', [KompetensiKeahlianController::class, 'deleteLogo'])->name('kompetensi-keahlian.delete-logo')->middleware('permission:menu_kompetensi_keahlian,delete');

    // Master Data — Rombel (Sumber: Rombongan Belajar & Peserta Didik)
    Route::get('/master-data/rombel', [\App\Http\Controllers\RombelController::class, 'index'])->name('rombel.index')->middleware('permission:menu_rombel,read');
    Route::get('/master-data/rombel/reguler', [\App\Http\Controllers\RombelController::class, 'reguler'])->name('rombel.reguler')->middleware('permission:menu_rombel,read');
    Route::get('/master-data/rombel/matpel', [\App\Http\Controllers\RombelController::class, 'matpel'])->name('rombel.matpel')->middleware('permission:menu_rombel,read');
    Route::get('/master-data/rombel/{id}/peserta-didik', [\App\Http\Controllers\RombelController::class, 'showPesertaDidik'])->name('rombel.peserta-didik')->middleware('permission:menu_rombel,read');

    // Master Data — Pembelajaran (Sumber: Pembelajaran, GTK, & Rombongan Belajar)
    Route::get('/master-data/pembelajaran', [\App\Http\Controllers\PembelajaranController::class, 'index'])->name('pembelajaran.index')->middleware('permission:menu_pembelajaran,read');
    Route::get('/master-data/pembelajaran/{id}', [\App\Http\Controllers\PembelajaranController::class, 'show'])->name('pembelajaran.show')->middleware('permission:menu_pembelajaran,read');

    // Master Data — Jadwal KBM (Anti-Bentrok & Integrasi Presensi/Jurnal Guru)
    Route::get('/master-data/jadwal-kbm', [\App\Http\Controllers\JadwalKbmController::class, 'index'])->name('jadwal-kbm.index')->middleware('permission:menu_jadwal_kbm,read');
    Route::get('/master-data/jadwal-kbm/pembelajaran-by-rombel', [\App\Http\Controllers\JadwalKbmController::class, 'getPembelajaranByRombel'])->name('jadwal-kbm.pembelajaran-by-rombel')->middleware('permission:menu_jadwal_kbm,read');
    Route::post('/master-data/jadwal-kbm/check-conflict', [\App\Http\Controllers\JadwalKbmController::class, 'checkConflictApi'])->name('jadwal-kbm.check-conflict')->middleware('permission:menu_jadwal_kbm,read');
    Route::post('/master-data/jadwal-kbm/pengaturan', [\App\Http\Controllers\JadwalKbmController::class, 'simpanPengaturan'])->name('jadwal-kbm.pengaturan')->middleware('permission:menu_jadwal_kbm,update');
    Route::post('/master-data/jadwal-kbm/auto-generate', [\App\Http\Controllers\JadwalKbmController::class, 'autoGenerate'])->name('jadwal-kbm.auto-generate')->middleware('permission:menu_jadwal_kbm,create');
    Route::get('/master-data/jadwal-kbm/guru-preferensi', [\App\Http\Controllers\JadwalKbmController::class, 'getGuruPreferensi'])->name('jadwal-kbm.guru-preferensi')->middleware('permission:menu_jadwal_kbm,read');
    Route::post('/master-data/jadwal-kbm/guru-preferensi', [\App\Http\Controllers\JadwalKbmController::class, 'simpanGuruPreferensi'])->name('jadwal-kbm.simpan-guru-preferensi')->middleware('permission:menu_jadwal_kbm,update');
    Route::get('/master-data/jadwal-kbm/cetak-induk', [\App\Http\Controllers\JadwalKbmController::class, 'cetakInduk'])->name('jadwal-kbm.cetak-induk')->middleware('permission:menu_jadwal_kbm,read');
    Route::get('/master-data/jadwal-kbm/cetak-guru', [\App\Http\Controllers\JadwalKbmController::class, 'cetakGuru'])->name('jadwal-kbm.cetak-guru')->middleware('permission:menu_jadwal_kbm,read');
    Route::get('/master-data/jadwal-kbm/cetak-rombel', [\App\Http\Controllers\JadwalKbmController::class, 'cetakRombel'])->name('jadwal-kbm.cetak-rombel')->middleware('permission:menu_jadwal_kbm,read');
    Route::post('/master-data/jadwal-kbm', [\App\Http\Controllers\JadwalKbmController::class, 'store'])->name('jadwal-kbm.store')->middleware('permission:menu_jadwal_kbm,create');
    Route::put('/master-data/jadwal-kbm/{id}', [\App\Http\Controllers\JadwalKbmController::class, 'update'])->name('jadwal-kbm.update')->middleware('permission:menu_jadwal_kbm,update');
    Route::delete('/master-data/jadwal-kbm/{id}', [\App\Http\Controllers\JadwalKbmController::class, 'destroy'])->name('jadwal-kbm.destroy')->middleware('permission:menu_jadwal_kbm,delete');

    // Master Data — Kalender Pendidikan
    Route::get('/master-data/kalender-pendidikan', [\App\Http\Controllers\KalenderPendidikanController::class, 'index'])->name('kalender-pendidikan.index')->middleware('permission:menu_kalender_pendidikan,read');
    Route::get('/master-data/kalender-pendidikan/events', [\App\Http\Controllers\KalenderPendidikanController::class, 'getEvents'])->name('kalender-pendidikan.events')->middleware('permission:menu_kalender_pendidikan,read');
    Route::post('/master-data/kalender-pendidikan', [\App\Http\Controllers\KalenderPendidikanController::class, 'store'])->name('kalender-pendidikan.store')->middleware('permission:menu_kalender_pendidikan,create');
    Route::get('/master-data/kalender-pendidikan/{id}', [\App\Http\Controllers\KalenderPendidikanController::class, 'show'])->name('kalender-pendidikan.show')->middleware('permission:menu_kalender_pendidikan,read');
    Route::put('/master-data/kalender-pendidikan/{id}', [\App\Http\Controllers\KalenderPendidikanController::class, 'update'])->name('kalender-pendidikan.update')->middleware('permission:menu_kalender_pendidikan,update');
    Route::delete('/master-data/kalender-pendidikan/{id}', [\App\Http\Controllers\KalenderPendidikanController::class, 'destroy'])->name('kalender-pendidikan.destroy')->middleware('permission:menu_kalender_pendidikan,delete');

    // Manajemen Data — Peserta Didik Aktif, Guru Aktif, & Tendik Aktif (Sumber: Peserta Didik & GTK Dapodik)
    Route::get('/manajemen-data/peserta-didik-aktif', [\App\Http\Controllers\PesertaDidikAktifController::class, 'index'])->name('peserta-didik-aktif.index')->middleware('permission:menu_peserta_didik_aktif,read');
    Route::get('/manajemen-data/peserta-didik-aktif/rombel-members', [\App\Http\Controllers\PesertaDidikAktifController::class, 'getRombelMembers'])->name('peserta-didik-aktif.rombel-members')->middleware('permission:menu_peserta_didik_aktif,read');
    Route::post('/manajemen-data/peserta-didik-aktif/upload-foto', [\App\Http\Controllers\PesertaDidikAktifController::class, 'uploadFoto'])->name('peserta-didik-aktif.upload-foto')->middleware('permission:menu_peserta_didik_aktif,update');
    Route::post('/manajemen-data/peserta-didik-aktif/bulk-upload-foto', [\App\Http\Controllers\PesertaDidikAktifController::class, 'bulkUploadFoto'])->name('peserta-didik-aktif.bulk-upload-foto')->middleware('permission:menu_peserta_didik_aktif,update');
    Route::post('/manajemen-data/peserta-didik-aktif/reset-password', [\App\Http\Controllers\PesertaDidikAktifController::class, 'resetPassword'])->name('peserta-didik-aktif.reset-password')->middleware('permission:menu_peserta_didik_aktif,update');
    Route::post('/manajemen-data/peserta-didik-aktif/toggle-koordinator', [\App\Http\Controllers\PesertaDidikAktifController::class, 'toggleKoordinator'])->name('peserta-didik-aktif.toggle-koordinator')->middleware('permission:menu_peserta_didik_aktif,update');
    Route::delete('/manajemen-data/peserta-didik-aktif/{id}/delete-foto', [\App\Http\Controllers\PesertaDidikAktifController::class, 'deleteFoto'])->name('peserta-didik-aktif.delete-foto')->middleware('permission:menu_peserta_didik_aktif,delete');
    Route::get('/manajemen-data/peserta-didik-aktif/{id}', [\App\Http\Controllers\PesertaDidikAktifController::class, 'show'])->name('peserta-didik-aktif.show')->middleware('permission:menu_peserta_didik_aktif,read');
    Route::get('/manajemen-data/peserta-didik-tidak-aktif', [\App\Http\Controllers\PesertaDidikTidakAktifController::class, 'index'])->name('peserta-didik-tidak-aktif.index')->middleware('permission:menu_peserta_didik_tidak_aktif,read');
    Route::post('/manajemen-data/peserta-didik-tidak-aktif/archive-grade12', [\App\Http\Controllers\PesertaDidikTidakAktifController::class, 'archiveGrade12'])->name('peserta-didik-tidak-aktif.archive-grade12')->middleware('permission:menu_peserta_didik_tidak_aktif,create');
    Route::get('/manajemen-data/peserta-didik-tidak-aktif/export', [\App\Http\Controllers\PesertaDidikTidakAktifController::class, 'exportExcel'])->name('peserta-didik-tidak-aktif.export')->middleware('permission:menu_peserta_didik_tidak_aktif,read');
    Route::get('/manajemen-data/peserta-didik-tidak-aktif/{id}', [\App\Http\Controllers\PesertaDidikTidakAktifController::class, 'show'])->name('peserta-didik-tidak-aktif.show')->middleware('permission:menu_peserta_didik_tidak_aktif,read');
    Route::get('/manajemen-data/guru-aktif', [\App\Http\Controllers\GuruAktifController::class, 'index'])->name('guru-aktif.index')->middleware('permission:menu_guru_aktif,read');
    Route::get('/manajemen-data/guru-aktif/{id}', [\App\Http\Controllers\GuruAktifController::class, 'show'])->name('guru-aktif.show')->middleware('permission:menu_guru_aktif,read');
    Route::get('/manajemen-data/tendik-aktif', [\App\Http\Controllers\TendikAktifController::class, 'index'])->name('tendik-aktif.index')->middleware('permission:menu_tendik_aktif,read');
    Route::get('/manajemen-data/tendik-aktif/{id}', [\App\Http\Controllers\TendikAktifController::class, 'show'])->name('tendik-aktif.show')->middleware('permission:menu_tendik_aktif,read');

    // Kartu Pelajar Digital — Layanan Cetak
    Route::get('/kartu-pelajar/cetak/{nisn}', [\App\Http\Controllers\KartuPelajarController::class, 'printSingle'])->name('kartu-pelajar.cetak-single');
    Route::get('/kartu-pelajar/cetak-rombel/{rombelId}', [\App\Http\Controllers\KartuPelajarController::class, 'printRombel'])->name('kartu-pelajar.cetak-rombel');

    // Arsip & Maintenance (Hanya Admin)
    Route::get('/maintenance', [\App\Http\Controllers\MaintenanceController::class, 'index'])->name('maintenance.index')->middleware('permission:menu_maintenance,read');
    Route::get('/maintenance/download', [\App\Http\Controllers\MaintenanceController::class, 'downloadArchive'])->name('maintenance.download')->middleware('permission:menu_maintenance,read');
    Route::post('/maintenance/clean', [\App\Http\Controllers\MaintenanceController::class, 'cleanOldData'])->name('maintenance.clean')->middleware('permission:menu_maintenance,delete');

    // Modul Wali Kelas (Peserta Didik Aktif & Tidak Aktif Terisolasi Per Kelas Binaan)
    Route::prefix('wali-kelas')->name('wali-kelas.')->group(function () {
        Route::get('/peserta-didik-aktif', [\App\Http\Controllers\WaliKelasController::class, 'pesertaDidikAktif'])->name('peserta-didik-aktif.index')->middleware('permission:menu_wali_kelas_aktif,read');
        Route::get('/peserta-didik-tidak-aktif', [\App\Http\Controllers\WaliKelasController::class, 'pesertaDidikTidakAktif'])->name('peserta-didik-tidak-aktif.index')->middleware('permission:menu_wali_kelas_tidak_aktif,read');
        Route::get('/peserta-didik/{id}', [\App\Http\Controllers\WaliKelasController::class, 'showPesertaDidik'])->name('peserta-didik.show')->middleware('permission:menu_wali_kelas_aktif,read');
        Route::get('/peserta-didik-tidak-aktif/{id}', [\App\Http\Controllers\WaliKelasController::class, 'showPesertaDidikTidakAktif'])->name('peserta-didik-tidak-aktif.show')->middleware('permission:menu_wali_kelas_tidak_aktif,read');

        // Presensi Kelas Binaan (Kontrol Kendala & Rekap PDF)
        Route::get('/presensi', [\App\Http\Controllers\WaliKelasController::class, 'presensi'])->name('presensi.index')->middleware('permission:menu_wali_kelas_presensi,read');
        Route::post('/presensi/manual', [\App\Http\Controllers\WaliKelasController::class, 'simpanPresensiManual'])->name('presensi.manual')->middleware('permission:menu_wali_kelas_presensi,update');
        Route::get('/presensi/pdf/{tipe}', [\App\Http\Controllers\WaliKelasController::class, 'downloadPdf'])->name('presensi.pdf')->middleware('permission:menu_wali_kelas_presensi,read');
    });

    // Realtime Server-Sent Events (SSE) & Polling Fallback
    Route::get('/realtime/stream', [\App\Http\Controllers\RealtimeController::class, 'stream'])->name('realtime.stream');
    Route::get('/realtime/poll', [\App\Http\Controllers\RealtimeController::class, 'poll'])->name('realtime.poll');
});

// Admin shortcut redirect
Route::get('/admin', function () {
    return redirect()->route('dashboard.admin');
});
